### ISSUE TITLE
Skip command skips two songs?

### ISSUE THREAD

**Issue by imLifeline** [Mesmaroth/discord-HathorBot#4]
Um so i took it for my server, but the skip command seems to skip two songs at the same time when the queue is more thn 2 songs like it works just fine with two songs on queue but i will skip to the third if there is one. ye is it just me or does it do that

**Comment by Mesmaroth** [comment]
No it should not skip two songs unless specified I believe. I will look into it. Thank you.

**Comment by imLifeline** [comment]
ight i tried to fix it but im so dum i couldnt even find where its given to skip a song is it in the skip command or is there a diff function?

**Comment by Mesmaroth** [comment]
I believe the skip command handles the skip using the global queue list. It's been a bit since I've looked at it. I will look into it after work.

**Comment by imLifeline** [comment]
Thank you!

**Comment by imLifeline** [comment]
and uh idk if i should open another issue for it but the play playlist command doesnt work if the playlist is made from youtube links, like it works for local but doesnt work for youtube linked one

**Comment by Mesmaroth** [comment]
Yes, feel free to make an new issue for that one. As I won't be getting to that just now.

**Comment by Mesmaroth** [comment]
Skipping should be fixed now. Please give it a try after pulling changes.

**Comment by imLifeline** [comment]
Yup it completely works, Thank you. Imma go make the playlist issue
